# Generated by Django 5.0.3 on 2024-06-03 16:13

import Game.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Morpion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('playerOne', models.CharField(max_length=10)),
                ('playerTwo', models.CharField(max_length=10)),
                ('scorePlayerOne', models.IntegerField(default=0)),
                ('scorePlayerTwo', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Morpion Games',
            },
        ),
        migrations.CreateModel(
            name='PlayersTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PongGame',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('playerOne', models.CharField(max_length=10)),
                ('playerTwo', models.CharField(max_length=10)),
                ('scorePlayerOne', models.IntegerField(default=0)),
                ('scorePlayerTwo', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PongGameIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerOne', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PongTournament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numberOfPlayer', models.IntegerField(validators=[Game.models.checkNumberOfPlayer])),
                ('current_round', models.IntegerField(default=1)),
                ('finished', models.BooleanField(default=False)),
                ('players', models.ManyToManyField(to='Game.playerstournament')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(default=1)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_matches', to='Game.playerstournament')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2_matches', to='Game.playerstournament')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='Game.playerstournament')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='Game.pongtournament')),
            ],
        ),
    ]
