# Generated by Django 5.0.3 on 2024-05-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pongtournament',
            name='current_round',
            field=models.IntegerField(default=1),
        ),
    ]
