# Generated by Django 5.0.3 on 2024-05-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_match_round_pongtournament_current_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='pongtournament',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
