# Generated by Django 5.0.3 on 2024-05-27 15:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0003_pongtournament_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='Morpion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('playerOne', models.CharField(max_length=10)),
                ('playerTwo', models.CharField(max_length=10)),
                ('scorePlayerOne', models.IntegerField(default=0)),
                ('scorePlayerTwo', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Morpion Games',
            },
        ),
    ]
