version: "3"

services:

  app:
    container_name: python
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./app:/app
    command:
      sh -c "python manage.py makemigrations && \
      python manage.py migrate && \
      gunicorn --certfile=/ssl/local.crt --keyfile=/ssl/local.key --bind 0.0.0.0:${APP_PORT} app.wsgi:application"
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DJANGO_AUTO_RENAME_MODEL: "true"
    depends_on:
      - db

  db:
    container_name: postgres
    env_file:
      - .env
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
