# Generated by Django 5.0.3 on 2024-05-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login42',
            field=models.CharField(max_length=50),
        ),
    ]
